name: Build IPQ-60xx

on:
  # schedule: # Каждый раз выполнять этот workflow github по расписанию
  #  - cron: '0 16 */5 * *'
  repository_dispatch:
  workflow_dispatch:
    inputs:
      docker:
        description: 'Should Docker be compiled?'
        required: false
        default: 'false'
      tag:
        description: 'libwrt version'
        required: false
        default: 'v25.12.1'

jobs:
  build:
    name: Compile ${{ matrix.device }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - device: AXT-1800
            config_file: './config/axt1800.config'
            workflow_name: 'AXT-1800'
    uses: ./.github/workflows/_openwrt-build-device.yml
    with:
      device: ${{ matrix.device }}
      config_file: ${{ matrix.config_file }}
      workflow_name: ${{ matrix.workflow_name }}
      repo_url: https://github.com/LiBwrt/LibWrt.git
      repo_branch: ${{ github.event.inputs.tag }}
      extra_config_file: ${{ github.event.inputs.docker == 'true' && './config/docker.config' || '' }}

  publish_release:
    name: Merge and release firmware
    needs: build
    runs-on: ubuntu-22.04
    if: success()
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Publish release
        uses: ./.github/actions/openwrt-publish-release
        with:
          release-tag-prefix: IPQ60xx-25.12-${{ github.event.inputs.tag }}
          source-url: ${{ github.inputs.repo_url }}
          source-branch: ${{ github.event.inputs.tag }}
          release-files: all-artifacts/firmware-*/*
