name: Build IPQ-60xx

on:
  # schedule: # Каждый раз выполнять этот workflow github по расписанию
  #  - cron: '0 16 * * *'
  repository_dispatch:
  workflow_dispatch:

env:
  REPO_URL_IMM: https://github.com/LiBwrt/openwrt-6.x
  REPO_BRANCH: main-nss
  FEEDS_CONF: feeds.conf.default
  DIY_P1_SH: ./sh/scripts-part1.sh
  DIY_P2_SH: ./sh/scripts-part2.sh
  DEFAULT_SETTING: ./default-settings
  UPLOAD_BIN_DIR: true
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  CACHE_TOOLCHAIN: true
  TZ: Europe/Berlin

jobs:
  build:
    name: Compile ${{ matrix.device }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - device: AXT-1800
            config_file: './config/axt1800.config'
            workflow_name: 'AXT-1800'

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Check Server Performance
      run: |
        echo "================================================="
        echo "           GitHub Actions operating environment details"
        echo "================================================="
        echo "CPU information:"
        lscpu
        echo "CPU thread count: $(nproc)"
        echo "-------------------------------------------------"
        echo "Memory information:"
        free -h
        echo "Swap partition size: $(grep SwapTotal /proc/meminfo | awk '{print $2/1024/1024 " GB"}')"
        echo "-------------------------------------------------"
        echo "Disk space information:"
        df -hT
        echo "-------------------------------------------------"
        echo "Operating system information:"
        uname -a
        lsb_release -a
        echo "================================================="

    - name: "Optimize Disk Space 1"
      uses: "hugoalh/disk-space-optimizer-ghaction@v0.8.1"
      with:
        operate_sudo: "True"
        general_include: ".+"
        general_exclude: |-
          ^GCC$
          ^G\+\+$
          Clang
          LLVM
        docker_include: ".+"
        docker_prune: "True"
        docker_clean: "True"
        apt_prune: "True"
        apt_clean: "True"
        os_swap: "True"

    - name: Optimize Disk Space 2
      run: |
        echo "Disk space before cleanup: "
        df -hT
        echo "Start cleaning up to free up more space..."
        sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo rm -rf /usr/share/swift /usr/local/.ghcup
        sudo docker image prune --all --force
        sudo rm -rf /opt/hostedtoolcache/CodeQL
        echo "Disk space after cleanup: "
        df -hT

    - name: Initialize environment ImmortalWrt
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        # Remove pre-installed packages that are not related to compilation
        sudo rm -rf /etc/apt/sources.list.d/*
        sudo -E apt-get -y update
        sudo -E apt-get -y purge azure-cli ghc* zulu* llvm* firefox google* dotnet* powershell openjdk* mongodb* moby* || true
        # Install compilation dependencies
        sudo bash -c 'bash <(curl -s https://build-scripts.immortalwrt.org/init_build_environment.sh)'
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get -y clean
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
        echo "WORKFLOW_NAME=${{ matrix.workflow_name }}" >> $GITHUB_ENV
        if [ -n "${{ github.event.inputs.tag }}" ]; then
          echo "TAG=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
        else
          echo "TAG=$REPO_BRANCH" >> $GITHUB_ENV
        fi

    - name: Clone source code
      working-directory: /workdir
      run: |
        df -hT $PWD
        git clone -b "${TAG}" $REPO_URL_IMM --single-branch --depth 1 openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
        cd openwrt

        # Removing Chinese Mirrors
        PROJECT_MIRRORS_FILE="./scripts/projectsmirrors.json"
        if [ -f "$PROJECT_MIRRORS_FILE" ]; then
          sed -i '/.cn\//d; /tencent/d; /aliyun/d' "$PROJECT_MIRRORS_FILE"
        fi
        git fetch --tags
        echo "OPENWRT_PATH=$PWD" >> $GITHUB_ENV

    - name: Load custom feeds
      run: |
        cd openwrt
        [ -e $GITHUB_WORKSPACE/$FEEDS_CONF ] && cp $GITHUB_WORKSPACE/$FEEDS_CONF ./feeds.conf.default
        ./scripts/feeds update -a
        chmod +x $GITHUB_WORKSPACE/$DIY_P1_SH
        $GITHUB_WORKSPACE/$DIY_P1_SH

    - name: Install feeds
      run: cd openwrt && ./scripts/feeds install -a

    - name: Extract plugin list
      id: extract-packages
      run: |
        echo "Extracting the plugin list from the source configuration file ${{ matrix.config_file }}..."
        grep 'luci-app-' ${{ matrix.config_file }} | \
        grep -v '^#' | \
        grep -v 'is not set' | \
        sed -e 's/CONFIG_PACKAGE_//g' -e 's/=y//g' | \
        sort > packages.txt || true

        echo "Check the generated file: "
        if [ -s packages.txt ]; then
          cat packages.txt
          echo "File generated successfully!"
        else
          echo "Warning: packages.txt is empty! This may be because the luci-app plugin is missing from the source configuration file."
          echo "No plugin information" > packages.txt
        fi

    - name: Upload plugin list products
      uses: actions/upload-artifact@main
      with:
        name: package-list-${{ matrix.device }}
        path: ${{ github.workspace }}/packages.txt

    - name: Load custom configuration
      run: |
        [ -e $GITHUB_WORKSPACE/$DEFAULT_SETTING ] && mv $GITHUB_WORKSPACE/$DEFAULT_SETTING openwrt/package/default-settings
        [ -d $GITHUB_WORKSPACE/files ] && mv $GITHUB_WORKSPACE/files openwrt/files
        [ -e "${{ matrix.config_file }}" ] && mv ${{ matrix.config_file }} openwrt/.config
        cd openwrt
        chmod +x $GITHUB_WORKSPACE/$DIY_P2_SH
        $GITHUB_WORKSPACE/$DIY_P2_SH
        make defconfig
        echo "Current diffconfig:"
        ./scripts/diffconfig.sh

    - name: Cache Toolchain
      uses: HiGarfield/cachewrtbuild@main
      if: env.CACHE_TOOLCHAIN != 'false'
      with:
        ccache: true
        mixkey: ${{ github.workflow }}-${{ matrix.workflow_name }}-${{ hashFiles(matrix.config_file, '**/scripts-part*.sh') }}
        prefix: ${{ env.OPENWRT_PATH }}

    - name: Download packages
      run: |
         cd openwrt
         make download -j$(nproc) || make download -j1 V=s
         find dl -size -1024c -exec rm -f {} \;

    - name: Build firmware
      run: |
        cd openwrt
        echo "Compilation is performed using the $(nproc) thread..."
        make -j$(expr $(nproc) + 1) || make -j1 V=s

    - name: Clean up temporary files after compilation
      if: success()
      run: |
        echo "Compilation complete. Now it's time to clean up the temporary compilation directory..."
        cd openwrt
        rm -rf build_dir tmp
        echo "Temporary files cleaned up!"

    - name: Organize firmware files
      id: organize
      run: |
        cd openwrt/bin/targets/*/*
        rm -rf packages
        echo "FIRMWARE_PATH=$PWD" >> $GITHUB_ENV
        cat $GITHUB_ENV

    - name: Upload firmware directory
      uses: actions/upload-artifact@main
      with:
        name: firmware-${{ matrix.device }}
        path: ${{ env.FIRMWARE_PATH }}


  publish_release:
    name: Merge and release firmware
    needs: build
    runs-on: ubuntu-22.04
    if: success()


    steps:
    - name: Download all firmware products
      uses: actions/download-artifact@v4
      with:
        path: all-artifacts

    - name: Rename the firmware file to avoid conflicts
      run: |
        echo "Start renaming common files to prevent upload conflicts..."
        for dir in all-artifacts/firmware-*; do
          DEVICE_NAME=$(basename "$dir" | sed 's/firmware-//')
          echo "Processing device: $DEVICE_NAME"
          cd "$dir"
          for file in version.buildinfo sha256sums profiles.json config.buildinfo feeds.buildinfo; do
            if [ -f "$file" ]; then
              mv "$file" "${DEVICE_NAME}-${file}"
              echo "  Rename: $file -> ${DEVICE_NAME}-${file}"
            fi
          done
          # While you're at it, also fix the filename references in sha256sums (optional)
          if [ -f "${DEVICE_NAME}-sha256sums" ]; then
            sed -i "s/ \*/ ${DEVICE_NAME}-/" "${DEVICE_NAME}-sha256sums"
          fi
          cd ../..
        done
        echo "All files have been renamed!"

    - name: Generate unified publishing tags and content.
      id: release-meta
      run: |
        DATE_SUFFIX=$(date +"%Y%m%d-%H%M")
        RELEASE_TAG="IPQ60xx-25.12-${{ env.REPO_BRANCH }}-${DATE_SUFFIX}"
        echo "Generated unified release tag: $RELEASE_TAG"
        echo "release_tag=$RELEASE_TAG" >> $GITHUB_ENV

        echo "### Firmware" > release-body.md
        echo "" >> release-body.md
        echo "This release includes the following devices:" >> release-body.md
        for dir in all-artifacts/firmware-*; do
          DEVICE_NAME=$(basename "$dir" | sed 's/firmware-//')
          echo "- **$DEVICE_NAME**" >> release-body.md
        done
        echo "" >> release-body.md
        echo "**Source code repository:** \`${{ env.REPO_URL_IMM }}\`" >> release-body.md
        echo "**Source code:** \`${{ env.REPO_BRANCH }}\`" >> release-body.md
        echo "" >> release-body.md
        echo "---" >> release-body.md

        echo "### Detailed list of plugins" >> release-body.md
        # Iterate through the plugin list directory for each device.
        for dir in all-artifacts/package-list-*; do
          DEVICE_NAME=$(basename "$dir" | sed 's/package-list-//')

          echo "" >> release-body.md
          echo "#### 🔌 $DEVICE_NAME" >> release-body.md
          sed 's/^/- /' "$dir/packages.txt" >> release-body.md
        done

    - name: Create a unified Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.release_tag }}
        body_path: release-body.md
        files: all-artifacts/firmware-*/*

    - name: Clean up old Releases
      uses: dev-drprasad/delete-older-releases@v0.1.0
      with:
        keep_latest: 10
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Clean up old workflow execution records
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 5
        keep_minimum_runs: 5

